/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbookingsystem;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author Glenn Lim Phang Zhen
 */
public class PaymentPage extends javax.swing.JDialog {
    double finalPrice;
    int rowIndex;
    String customerName, roomNo;
    Receipt payment;
    Booking bookingPayment;
    boolean fromBooking = true;
    
    /**
     * Creates new form PaymentPage
     */
    
    //constructor for getting data from the table
    public PaymentPage(java.awt.Frame parent, boolean modal, Receipt payment, String roomNo, String customerName,int row) {
        super(parent, modal);
        initComponents();
        lblTotalPrice.setText("RM " + String.valueOf(payment.getPrice()));
        this.finalPrice = payment.getPrice();
        lblRoomNo.setText(roomNo);
        this.rowIndex = row;
        this.customerName = customerName;
        this.payment = payment;
        this.roomNo = roomNo;
        fromBooking = false ;  
    }
    
    //constructor for opening payment page after a booking
    public PaymentPage(java.awt.Frame parent, boolean modal, Booking payment) {
        super(parent, modal);
        initComponents();
        lblTotalPrice.setText("RM " + String.valueOf(payment.getPrice()));
        lblRoomNo.setText(payment.getRoomNo());
        this.finalPrice = payment.getPrice();
        bookingPayment = payment;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTotalPrice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();
        txtPayed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblRoomNo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 50)); // NOI18N
        jLabel2.setText("Getwellsoon Hotel");

        jLabel1.setText("Total Price : ");

        jLabel3.setText("Payed  :");

        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblTotalPrice.setText("lblTotalPrice");

        jLabel5.setText("Change :");

        txtPayed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPayedKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPayedKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setText("RoomNo");

        lblRoomNo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lblRoomNo.setText("RoomNo");

        jLabel6.setText("RM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel6)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPayed, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblTotalPrice)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(83, 83, 83))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblRoomNo))
                    .addComponent(jLabel2))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomNo)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(89, 89, 89))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String input = txtPayed.getText();
        double userPay;
        try {
            userPay = Double.valueOf(input);
            if ((userPay - finalPrice) >= 0) {
                double change = userPay - finalPrice;
                this.setVisible(false);        
                if (fromBooking) {
                    JOptionPane.showMessageDialog(null, "Successfully paid! And added booking");
                    bookingPayment.Pay(userPay);
                    bookingPayment.writeBooking();
                    Invoice paymentInvoice = new Invoice(bookingPayment);
                    paymentInvoice.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Successfully paid!");
                    this.payment.Pay(this.rowIndex, userPay, change);
                    Invoice paymentInvoice = new Invoice(payment, roomNo, customerName, "paid");
                    paymentInvoice.setVisible(true);
                }
                                  
            } else {
                JOptionPane.showMessageDialog(null, "Please make sure customer pay the right amount.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e, "Invalid Input Type", HEIGHT);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PaymentPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPayedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayedKeyPressed
        
        String input = txtPayed.getText();
        double userPay;
        try {
            userPay = Double.valueOf(input);
            if ((userPay - finalPrice) >= 0) {
            double change = userPay - finalPrice;
            lblChange.setText("RM " + String.valueOf(change));
            } else {
                lblChange.setText("");
            }   
        } catch (NumberFormatException e) {
        }
      
    }//GEN-LAST:event_txtPayedKeyPressed

    private void txtPayedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayedKeyReleased

        String input = txtPayed.getText();
        double userPay;
        try {
            userPay = Double.valueOf(input);
            if ((userPay - finalPrice) >= 0) {
            double change = userPay - finalPrice;
            lblChange.setText("RM "+String.valueOf(change));
            } else {
                lblChange.setText("");
            } 
        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_txtPayedKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (fromBooking) {
            boolean writeStatus = bookingPayment.writeBooking(); // write unpaid booking if user decide to not pay and close the form
            if (writeStatus) {
                JOptionPane.showMessageDialog(null, "Booking has been added. But payment still pending.");
            } else {
                JOptionPane.showMessageDialog(null, "There was an error writing booking.");
            }            
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblRoomNo;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTextField txtPayed;
    // End of variables declaration//GEN-END:variables
}
